on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || github.sha }}-${{ github.base_ref || '' }}
  cancel-in-progress: true

name: rcc

jobs:
  test-install-scripts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - dm
          - duckdb
          - igraph
          - igraph2
          - r-sb
          - rmariadb 
          - rpostgres

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        
      - name: "Install ${{ matrix.package }}"
        run: sh ./install-${{ matrix.package }}.sh
